### ISSUE TITLE
Missing remote-inbound-rtp and remote-outbound-rtp stats in Firefox and Chrome

### ISSUE THREAD

**Issue by dryarullin** [pion/webrtc#2663]
### Your environment.
  - Version: 4
  - Browser: Firefox - 122.0, Chrome - 121.0.6167.140
  - Other Information - https://github.com/pion/interceptor/issues/165

### What did you do?
Sending a single audio track from browser to pion webrtc, acting as echo server.
I check the availability of statis using a browser client (about:webrtc and chrome://webrtc-internals).

```
type message struct {
	Type    string `json:"type"`
	Payload string `json:"payload"`
}

func messageReceiver(conn *websocket.Conn, msgch chan message) {
	m := message{}
	for {
		if err := websocket.ReadJSON(conn, &m); err != nil {
			close(msgch)
			return
		} else {
			msgch <- m
		}
	}
}

func main() {
	m := &webrtc.MediaEngine{}
	m.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus, ClockRate: 48000},
	}, webrtc.RTPCodecTypeAudio)

	api := webrtc.NewAPI(webrtc.WithMediaEngine(m))

	upgrader := websocket.Upgrader{
		CheckOrigin: func(r *http.Request) bool {
			return true
		},
	}

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		data, err := ioutil.ReadFile("index.html")
		if err != nil {
			log.Println(err)
		}
		fmt.Fprintf(w, string(data))
	})

	http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			return
		}
		defer conn.Close()

		msgch := make(chan message)
		go messageReceiver(conn, msgch)

		peerConnection, err := api.NewPeerConnection(webrtc.Configuration{
			ICEServers: []webrtc.ICEServer{
				{
					URLs: []string{"stun:stun.l.google.com:19302"},
				},
			},
		})
		if err != nil {
			return
		}

		var localAudioTrack *webrtc.TrackLocalStaticRTP = nil
		peerConnection.OnTrack(func(remoteTrack *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
			for {
				rtpPacket, _, err := remoteTrack.ReadRTP()
				if err != nil {
					return
				}
				if localAudioTrack == nil {
					continue
				}
				err = localAudioTrack.WriteRTP(rtpPacket)
				if err != nil {
					return
				}
			}
		})

		peerConnection.OnICECandidate(func(c *webrtc.ICECandidate) {
			if c == nil {
				return
			}
			outbound, marshalErr := json.Marshal(c.ToJSON())
			if marshalErr != nil {
				panic(marshalErr)
			}
			websocket.WriteJSON(conn, &message{Type: "candidate", Payload: string(outbound)})
		})

		localAudioTrack, err = webrtc.NewTrackLocalStaticRTP(webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus}, "audio", "pion")
		if err != nil {
			return
		}
		_, err = peerConnection.AddTrack(localAudioTrack)
		if err != nil {
			return
		}

		for {
			select {
			case m, ok := <-msgch:
				if ok {
					switch m.Type {
					case "offer":
						{
							desc := webrtc.SessionDescription{Type: webrtc.SDPTypeOffer, SDP: m.Payload}
							err = peerConnection.SetRemoteDescription(desc)
							if err != nil {
								goto close
							}
							answer, err := peerConnection.CreateAnswer(nil)
							if err != nil {
								goto close
							}
							err = peerConnection.SetLocalDescription(answer)
							if err != nil {
								goto close
							}

							websocket.WriteJSON(conn, &message{Type: "answer", Payload: answer.SDP})
						}
					case "candidate":
						{
							candidate := webrtc.ICECandidateInit{Candidate: m.Payload}
							err := peerConnection.AddICECandidate(candidate)
							if err != nil {
							}
						}
					}
				} else {
					goto close
				}
			}
		}
	close:
	})

	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Printf("httpListenAndServe() failed: %v\n", err)
	}
}

```

### What did you expect?
I'd expect remote-inbound-rtp and remote-outbound-rtp stats to be available on the browser.

### What happened?
Only inbound-rtp and outbound-rtp stats are available.

**Comment by Sean-Der** [comment]
Hi @dryarullin 

This is probably happening because you don’t have RTCP Reports enabled. When you create the API object you needed to call `RegisterDefaultInterceptors`

In newer versions of Pion this isn’t the case though. When creating an API object they should be enabled.

Try using the latest version of Pion and this should be fixed!

**Comment by yagafonov** [comment]
@Sean-Der Hello!
I faced similar problem, I have the last pion version, and run the same code example. I found that roundTripTime key is not presented neither in remote-outbound-rtp nor in remote-inbound-rtp. As far as I understand what's hapenning these stat must have been presented here. Am I wrong? Or It is a bug?
Thank you for attention.

**Comment by neilyoung** [comment]
2025 here: Still not working. And yes, RegisterDefaultInterceptors is called

**Comment by JoTurk** [comment]
@neilyoung Hello, Can you open an issue with your problem, and version used, and a simple reproduce code if possible?

**Comment by neilyoung** [comment]
@JoeTurki I just took the sample code you provided here 

https://github.com/pion/webrtc/blob/v3.3.5/examples/stats/main.go

and added `fmt.Println(stats.RemoteOnboundRTPStreamStats)`. 

But a browser app working against the same MediaServer has no problems to obtain Remote Stats at all. It also does not have anything to do with Firefox. It is just a suspicion, that PION 3.3.5 is not able to derive RTCP information properly.

Sorry, can't provide sample code. Your stat sample is also not working stand alone, since it refers to a signaling module, which I can't find in the code.

**Comment by JoTurk** [comment]
@neilyoung Hello is it possible for you to upgrade to pion v4?

**Comment by neilyoung** [comment]
I can try

**Comment by neilyoung** [comment]
Same

```
Stats for: video/H264
OutboundRTPStreamStats
        PacketsSent: 2038
        BytesSent: 1942041
        HeaderBytesSent: 24456
        NACKCount: 0
        FIRCount: 0
        PLICount: 0

RemoteInboundRTPStreamStats:
        PacketsReceived: 0
        PacketsLost: 0
        Jitter: 0
        RoundTripTime: 0s
        TotalRoundTripTime: 0s
        FractionLost: 0
        RoundTripTimeMeasurements: 0
```

**Comment by neilyoung** [comment]
Oh, weird. Seems I forgot to actively sender.ReadRTCP() and/or receiver.ReadRTCP() in a go routine. Then the Remote stats come
